FROM rust:latest AS builder

RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

WORKDIR /consul-api-agent

COPY ./ .

RUN cargo build --target x86_64-unknown-linux-musl --release --bin consul-api-agent

FROM scratch

WORKDIR /consul-api-agent

COPY --from=builder /consul-api-agent/target/x86_64-unknown-linux-musl/release/consul-api-agent ./

ENTRYPOINT ["/consul-api-agent/consul-api-agent"]