FROM rust:latest AS builder

RUN update-ca-certificates

WORKDIR /consul-api-sidecar

COPY ./ .

RUN cargo build --release --bin consul-api-sidecar

FROM gcr.io/distroless/cc

WORKDIR /consul-api-sidecar

COPY --from=builder /consul-api-sidecar/target/release/consul-api-sidecar ./

ENTRYPOINT ["/consul-api-sidecar/consul-api-sidecar"]