FROM rust:latest AS builder

RUN update-ca-certificates

WORKDIR /consul-api-agent

COPY ./ .

RUN cargo build --release --bin consul-api-agent

FROM gcr.io/distroless/cc

WORKDIR /consul-api-agent

COPY --from=builder /consul-api-agent/target/release/consul-api-agent ./

ENTRYPOINT ["/consul-api-agent/consul-api-agent"]