FROM rust:latest AS builder

RUN rustup target add x86_64-unknown-linux-musl
RUN apt update && apt install -y musl-tools musl-dev
RUN update-ca-certificates

WORKDIR /consul-api-sidecar

COPY ./ .

RUN cargo build --target x86_64-unknown-linux-musl --release --bin consul-api-sidecar

FROM scratch

WORKDIR /consul-api-sidecar

COPY --from=builder /consul-api-sidecar/target/x86_64-unknown-linux-musl/release/consul-api-sidecar ./

ENTRYPOINT ["/consul-api-sidecar/consul-api-sidecar"]